# Header

menu:
  主页: /
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/mikewolfli"
  weibo: "http://www.weibo.com/u/2633578007"
  rss: "#"
  zhihu: "https://www.zhihu.com/people/mikewolfli"
  #douban: "#"
  mail: "mailto: mikewolfli@163.com"
  #facebook: "#"
  google: "https://plus.google.com/u/0/115870229318093051142"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://avatars2.githubusercontent.com/u/1853069?v=3&s=400"

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: mikewolfli

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: 'Archives'
  tagcloud: 'Tags'
  friends: 'Links'
  aboutme: 'About me'

friends:
  中文博客: http://blog.csdn.net/mikewolfli


aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家